chart:
  height: "50px"
  fontFamily: "var(--paper-ha-card_-_font-family)"
  sparkline:
    enabled: true
  parentHeightOffset: 0
tooltip:
  enabled: false
grid:
  show: false
  padding:
    left: -25
    right: -17
    top: -15
dataLabels:
  show: true
  formatter: |
    EVAL:function(value) {
      return value.toFixed(1) + "â‚¬";
    }
  style:
    fontSize: "12px"
    colors: ["var(--card-background-color)"]
  background:
    enabled: false
plotOptions:
  bar:
    borderRadius: 6
    borderRadiusApplication: end
    columnWidth: "90%"
